### ISSUE TITLE
/metrics endpoint stops working after a while

### ISSUE THREAD

**Issue by roelywoely** [theodore86/github-rate-limits-exporter#49]
At first, when I run the app in Docker it works:
```bash
❯ curl http://localhost:10050/metrics
# HELP python_gc_objects_collected_total Objects collected during gc
# TYPE python_gc_objects_collected_total counter
python_gc_objects_collected_total{generation="0"} 573.0
python_gc_objects_collected_total{generation="1"} 109.0
python_gc_objects_collected_total{generation="2"} 0.0
...
```
Then, after a while (5-60 minutes or so) it stops working:
```bash
[INFO - 2023-01-09 13:14:26,493]: HTTP metrics server started on [0.0.0.0:10050]
[DEBUG - 2023-01-09 13:23:07,120]: Collected metrics for {accountname} account
Traceback (most recent call last):
  File "/opt/venv/lib/python3.11/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/opt/venv/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/opt/venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/opt/venv/lib/python3.11/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/urllib3/connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7fb0159c8ad0>, 'Connection to api.github.com timed out. (connect timeout=15)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venv/lib/python3.11/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /rate_limit (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fb0159c8ad0>, 'Connection to api.github.com timed out. (connect timeout=15)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/prometheus_client/exposition.py", line 129, in prometheus_app
    status, headers, output = _bake_output(registry, accept_header, accept_encoding_header, params, disable_compression)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/prometheus_client/exposition.py", line 105, in _bake_output
    output = encoder(registry)
             ^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/prometheus_client/exposition.py", line 198, in generate_latest
    for metric in registry.collect():
  File "/opt/venv/lib/python3.11/site-packages/prometheus_client/registry.py", line 97, in collect
    yield from collector.collect()
               ^^^^^^^^^^^^^^^^^^^
  File "/app/github_rate_limits_exporter/collector.py", line 80, in collect
    rate_limits = self.rate_limits
                  ^^^^^^^^^^^^^^^^
  File "/app/github_rate_limits_exporter/collector.py", line 69, in rate_limits
    rate_limits = self._api.get_rate_limit()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/github/MainClass.py", line 201, in get_rate_limit
    headers, data = self.__requester.requestJsonAndCheck("GET", "/rate_limit")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/github/Requester.py", line 354, in requestJsonAndCheck
    *self.requestJson(
     ^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/github/Requester.py", line 454, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/github/Requester.py", line 528, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(
                                      ^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/github/Requester.py", line 555, in __requestRaw
    response = cnx.getresponse()
               ^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/github/Requester.py", line 127, in getresponse
    r = verb(
        ^^^^^
  File "/opt/venv/lib/python3.11/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/requests/adapters.py", line 553, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /rate_limit (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fb0159c8ad0>, 'Connection to api.github.com timed out. (connect timeout=15)'))
```
Is there a way to easily debug which requests are being made exactly to Github?

**Comment by theodore86** [comment]
Hi @roelywoely, 

It seems that there is connection issue towards ``api.github.com``, at least the python ``requests`` library is complaining about the ``Max retries exceeded``, i have faced the same issue whenever my internet connection is unstable.

As a quick workaround you can set the restart policy to ``always`` when it is deployed on kubernetes or docker-compose. In such case whenever the process is exiting with statuc code 1 then the docker daemon or kubelet will try to restart.

Regarding the loglevel, if you check the ``cli.py`` module and ``utils.py``:

```python
    parser.add_argument(
        "-v",
        dest="verbosity",
        default=0,
        action="count",
        help="Increase verbosity level (-vv for more)",
    )
```

you can increase the verbosity up to 5 (-vvvvv) to set the loglevel to ``DEBUG``, moreover, there is an easier way to make it configurable try this:

```python
    parser.add_argument(
        "-v",
        dest="verbosity",
        default=os.getenv('LOGLEVEL', 0),
        action="count",
        help="Increase verbosity level (-vv for more)",
    )
```

How did you deployed the process? through docker-compose?

**Comment by roelywoely** [comment]
> Hi @roelywoely, thanks for your feedback, appreciate it,
> 
> It seems that there is a network instability towards the `api.github.com`, at least the python `requests` library is complaining about the `Max retries exceeded`:
> 
> ```python
> requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /rate_limit (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fb0159c8ad0>, 'Connection to api.github.com timed out. (connect timeout=15)'))
> ```
> 
> i have faced the same issue whenever my internet connection is unstable (connections breaks for more than 1 minute). In either case kubelet or docker-compose or docker restart policy should try to restart the process whenever it exists with **_non-zero status_** (this requires configuration)
> 
> How did you deploy the exporter? on bare-metal ? on docker or on k8s?

I deployed it using Docker. I'm having this issue both on a AWS EC2 instance and on my local machine.
I did not set the Docker restart policy. I will try that. However, it feels more like a workaround than a proper fix. Are there any other things that can be done to debug this a bit deeper? (This is also the reason why I wanted to set the log level to `DEBUG`, however this didn't provide any useful info)
I would be curious to see which curl requests are being performed and how many times. Thanks in advance :)

**Comment by roelywoely** [comment]
@theodore86 Thanks for your reply. 

> How did you deploy the exporter? on docker or on k8s?

I'm using Docker, not k8s. This problem occurs on both my local machine and an AWS EC2 instance. Restart policy is set to `always`. The problem is that whenever the container crashes, it doesn't restart. So probably it needs a Docker healthcheck. But that feels more like a patch, I'd prefer to try to fix the root cause.

> Btw, did you check the net_conntrack_dialer_conn_failed_total prometheus metrics? or the net_connetrac_* metrics in general?

Do you mean in Prometheus, not in the output of the `/metrics` endpoint of the Docker container of this exporter? I don't see how it can contain relevant information, as locally I'm not running Prometheus and the problem still occurs (I'm not using the provided `docker-compose.yml`).

Also interesting: Whenever I run `watch -n 10 "curl 'http://localhost:10050/metrics'"` (locally, outside of the Docker container) the issue seems to be resolved and everything works fine. However, after an hour or so, it starts to fail with:
```bash
[DEBUG - 2023-01-11 11:47:58,833]: GET https://api.github.com/rate_limit {'Authorization': 'token (oauth token removed)', 'User-Agent': 'PyGithub/Python'} None ==> 401 {'server': 'GitHub.com', 'date': 'Wed, 11 Jan 2023 11:47:58 GMT', 'content-type': 'application/json; charset=utf-8', 'content-length': '80', 'x-github-media-type': 'github.v3; format=json', 'x-ratelimit-limit': '60', 'x-ratelimit-remaining': '60', 'x-ratelimit-reset': '1673441278', 'x-ratelimit-used': '0', 'x-ratelimit-resource': 'core', 'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset', 'access-control-allow-origin': '*', 'strict-transport-security': 'max-age=31536000; includeSubdomains; preload', 'x-frame-options': 'deny', 'x-content-type-options': 'nosniff', 'x-xss-protection': '0', 'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin', 'content-security-policy': "default-src 'none'", 'vary': 'Accept-Encoding, Accept, X-Requested-With', 'x-github-request-id': 'XXXXXXXXXXXXX'} {"message":"Bad credentials","documentation_url":"https://docs.github.com/rest"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/prometheus_client/exposition.py", line 129, in prometheus_app
    status, headers, output = _bake_output(registry, accept_header, accept_encoding_header, params, disable_compression)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/prometheus_client/exposition.py", line 105, in _bake_output
    output = encoder(registry)
             ^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/prometheus_client/exposition.py", line 198, in generate_latest
    for metric in registry.collect():
  File "/opt/venv/lib/python3.11/site-packages/prometheus_client/registry.py", line 97, in collect
    yield from collector.collect()
               ^^^^^^^^^^^^^^^^^^^
  File "/app/github_rate_limits_exporter/collector.py", line 80, in collect
    rate_limits = self.rate_limits
                  ^^^^^^^^^^^^^^^^
  File "/app/github_rate_limits_exporter/collector.py", line 69, in rate_limits
    rate_limits = self._api.get_rate_limit()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/github/MainClass.py", line 201, in get_rate_limit
    headers, data = self.__requester.requestJsonAndCheck("GET", "/rate_limit")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/github/Requester.py", line 353, in requestJsonAndCheck
    return self.__check(
           ^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/github/Requester.py", line 378, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.BadCredentialsException: 401 {"message": "Bad credentials", "documentation_url": "https://docs.github.com/rest"}
```

**Comment by theodore86** [comment]
Hi @roelywoely, thank you for using this project, appreciate it!

The github-rate-limits-exporter uses the _python prometheus-client_, the main focus on the ``/metrics`` endpoint is tho provide the ``github_rate_limits_*`` metrics but i have also include some *default* metrics of the prometheus-client library like ``process_cpu_*`` and ``net_conntrack_*`` which are pretty useful to monitor the exporter through grafana or prometheus (btw i was thinking to include a dashboard with some system/health monitoring graphs of the exporter).  Check the output of your curl command you will find some extra metrics regarding the exporter itself.

Regarding the first case:

```
github.GithubException.BadCredentialsException: 401 {"message": "Bad credentials", "documentation_url": "https://docs.github.com/rest"}
```

Most probably the ``401`` http status indicates an expired token or the provided credentials in general are invalid. Maybe you have set ``1 hour`` of expiration of the generated PAT (Personal Access Token)?

The second case indicates network instability:

```
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /app/installations/XXXXXXXX/access_tokens (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fa789c75bd0>, 'Connection to api.github.com timed out. (connect timeout=None)'))
```

In reality the exporter is trying to establish an TCP connection to retrieve the latest metrics from the ``api.github.com`` but it fails after the *configured* max retries. I suppose it has to do with the networking on the given network topology, i couldn't either reproduce it but i will use the ``watch -n 10 "curl 'http://localhost:10050/metrics``

**Comment by roelywoely** [comment]
@theodore86
> but i have also include the default metrics of the [prometheus-client](https://github.com/prometheus/client_python) library like process_cpu_*, process_mem_* and net_conntrack_* (network related metrics)

I don't see those metrics:
```
# HELP python_gc_objects_collected_total Objects collected during gc
# TYPE python_gc_objects_collected_total counter
python_gc_objects_collected_total{generation="0"} 660.0
python_gc_objects_collected_total{generation="1"} 22.0
python_gc_objects_collected_total{generation="2"} 0.0
# HELP python_gc_objects_uncollectable_total Uncollectable object found during GC
# TYPE python_gc_objects_uncollectable_total counter
python_gc_objects_uncollectable_total{generation="0"} 0.0
python_gc_objects_uncollectable_total{generation="1"} 0.0
python_gc_objects_uncollectable_total{generation="2"} 0.0
# HELP python_gc_collections_total Number of times this generation was collected
# TYPE python_gc_collections_total counter
python_gc_collections_total{generation="0"} 85.0
python_gc_collections_total{generation="1"} 7.0
python_gc_collections_total{generation="2"} 0.0
# HELP python_info Python platform information
# TYPE python_info gauge
python_info{implementation="CPython",major="3",minor="11",patchlevel="1",version="3.11.1"} 1.0
# HELP process_virtual_memory_bytes Virtual memory size in bytes.
# TYPE process_virtual_memory_bytes gauge
process_virtual_memory_bytes 2.0525056e+08
# HELP process_resident_memory_bytes Resident memory size in bytes.
# TYPE process_resident_memory_bytes gauge
process_resident_memory_bytes 4.388864e+07
# HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
# TYPE process_start_time_seconds gauge
process_start_time_seconds 1.67344913489e+09
# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
# TYPE process_cpu_seconds_total counter
process_cpu_seconds_total 2.9699999999999998
# HELP process_open_fds Number of open file descriptors.
# TYPE process_open_fds gauge
process_open_fds 7.0
# HELP process_max_fds Maximum number of open file descriptors.
# TYPE process_max_fds gauge
process_max_fds 1.048576e+06
# HELP github_rate_limits_core API requests in core per hour
# TYPE github_rate_limits_core gauge
github_rate_limits_core{account="myaccount",type="limit"} 15000.0 1673450570979
github_rate_limits_core{account="myaccount",type="used"} 5988.0 1673450570979
github_rate_limits_core{account="myaccount",type="remaining"} 9012.0 1673450570979
github_rate_limits_core{account="myaccount",type="reset"} 1.673450949e+09 1673450570979
# HELP github_rate_limits_search API requests in search per hour
# TYPE github_rate_limits_search gauge
github_rate_limits_search{account="myaccount",type="limit"} 30.0 1673450570979
github_rate_limits_search{account="myaccount",type="used"} 0.0 1673450570979
github_rate_limits_search{account="myaccount",type="remaining"} 30.0 1673450570979
github_rate_limits_search{account="myaccount",type="reset"} 1.67345063e+09 1673450570979
# HELP github_rate_limits_graphql API requests in graphql per hour
# TYPE github_rate_limits_graphql gauge
github_rate_limits_graphql{account="myaccount",type="limit"} 12500.0 1673450570979
github_rate_limits_graphql{account="myaccount",type="used"} 0.0 1673450570979
github_rate_limits_graphql{account="myaccount",type="remaining"} 12500.0 1673450570979
github_rate_limits_graphql{account="myaccount",type="reset"} 1.67345417e+09 1673450570979
# HELP github_rate_limits_integration_manifest API requests in integration_manifest per hour
# TYPE github_rate_limits_integration_manifest gauge
github_rate_limits_integration_manifest{account="myaccount",type="limit"} 5000.0 1673450570979
github_rate_limits_integration_manifest{account="myaccount",type="used"} 0.0 1673450570979
github_rate_limits_integration_manifest{account="myaccount",type="remaining"} 5000.0 1673450570979
github_rate_limits_integration_manifest{account="myaccount",type="reset"} 1.67345417e+09 1673450570979
# HELP github_rate_limits_code_scanning_upload API requests in code_scanning_upload per hour
# TYPE github_rate_limits_code_scanning_upload gauge
github_rate_limits_code_scanning_upload{account="myaccount",type="limit"} 1000.0 1673450570979
github_rate_limits_code_scanning_upload{account="myaccount",type="used"} 0.0 1673450570979
github_rate_limits_code_scanning_upload{account="myaccount",type="remaining"} 1000.0 1673450570979
github_rate_limits_code_scanning_upload{account="myaccount",type="reset"} 1.67345417e+09 1673450570979
```

> Most probably the 401 http status indicates an expired token or the provided credentials in general are invalid.
Maybe you have set the token expiration time to 1 hour ? Are you sing PAT as GITHUB_AUTH_TYPE?

No, the `GITHUB_AUTH_TYPE` is set to `app`.
Where can I find the token expiration time? I searched the source code for `expiration` but I couldn't find it, it's also not in the Github app settings.

What potentially might be the issue is that the app isn't return exit code 1 whenever the API call to Github fails, therefore the container isn't restarted.

**Comment by theodore86** [comment]
> What potentially might be the issue is that the app isn't return exit code 1 whenever the API call to Github fails, therefore the container isn't restarted.

Seems like is restarted correctly:

```python
gh-rl-exporter  |     raise self.__createException(status, responseHeaders, output)
gh-rl-exporter  | github.GithubException.BadCredentialsException: 401 {"message": "Bad credentials", "documentation_url": "https://docs.github.com/rest"}

gh-rl-exporter exited with code 1

gh-rl-exporter  | [INFO - 2023-01-11 16:02:01,438]: Register collector for "theodore86" Github account
alertmanager    | ts=2023-01-11T16:02:01.470Z caller=cluster.go:705 level=info component=cluster msg="gossip not settled" polls=0 before=0 now=1 elapsed=2.000311232s
gh-rl-exporter  | [ERROR - 2023-01-11 16:02:01,864]: 401 {"message": "Bad credentials", "documentation_url": "https://docs.github.com/rest"}
```

```sh
docker run -p 10050:10050 -d \
  --name gh-rl-exporter \
  --restart on-failure \
  -e GITHUB_AUTH_TYPE=app \
  -e GITHUB_ACCOUNT=my_account_name \
  -e GITHUB_APP_ID=11111 \
  -e GITHUB_APP_INSTALLATION_ID=22222222 \
  -e GITHUB_APP_PRIVATE_KEY_PATH=/app/test.rsa \
  -e GITHUB_LOG_LEVEL=4 \
  --mount type=bind,source=/ws/test.rsa,target=/app/test.rsa,readonly \
  exporter:latest
```

> Where can I find the token expiration time? I searched the source code for expiration but I couldn't find it, it's also not in the Github app settings.

Apologies my mistake the Github App does not have expiration dat only the PAT, most probably something with the App settings is not configured properly, just tested and it works fine.

> but i have also include the default metrics of the [prometheus-client](https://github.com/prometheus/client_python) library like process_cpu_, process_mem_ and net_conntrack_* (network related metrics)

I don't see those metrics:

Apoligies my mistake here, the ``net_conntrack_*`` are the prometheis metrics itself, the gc,platform and process metrics are given by default through the prometeus client python library so yea we can only check the cpu, memory

**Comment by theodore86** [comment]
@roelywoely thanks for your issue, in reality there is a bug on the implementation.

At first, check this ticket regarding the [PyGithub](https://github.com/PyGithub/PyGithub/pull/1986), it says that the JWT token expires every hour (60 minutes) and there is a pending work to support renewal of the tokens.

So, here comes the issue, when token expires the program raises ``github.GithubException.BadCredentialsException`` which should be gracefully handle by the ``except`` clause in the ``line 57`` in ``__init__.py`` but the exception is not raised in the main thread:) check the implementation of the [start_http_server](https://github.com/prometheus/client_python/blob/1fd0ded5f8c9e7101471ea06198d88427728ff50/prometheus_client/exposition.py#L173) so it remains unhadle, in any case, the root cause is the JWT token expiration so i need to perform some modification on the exporter to somehow refresh the token. Issue starts from the [line 48](https://github.com/theodore86/github-rate-limits-exporter/blob/main/github_rate_limits_exporter/__init__.py#L48) where the token is retrieved only once for the lifecycle of the exporter, most probably i need to move this responsiblity to the ``GithubRateLimitCollector``.

**Comment by theodore86** [comment]
@roelywoely, i have manage ([here](https://github.com/theodore86/github-rate-limits-exporter/tree/62-githubapp-installation-access-token-refresh-mechanism)) to overcome the Github APP Token limitation (the 1 hour token expiration) and the fact that PyGithub doesn't support token renewal on the http authorization header, most probably by tommorow i will integrate the changes into the main branch, later on i will deal with the unhandle exceptions part.
